language: node_js # 设置语言

node_js:
  - "8" # 设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    
install:
  - npm install  # 安装依赖

script:
  - gulp clean  # 清除
  - gulp # 生成

after_script:
  - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config user.name "leochan2017"  # 修改name
  - git config user.email "leochan2017@gmail.com"  #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master  #Travis_Token是在Travis中配置环境变量的名称

env:
 global:
   - GH_REF: git@github.com:leochan2017/kms-editors.git  # 设置GH_REF

notifications:
  email:
    - leochan2017@gmail.com
  on_success: change
  on_failure: always