language: node_js # 设置语言
node_js:
  - "8" # 设置相应的版本
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容
install:
  - npm install  # 安装依赖
script:
  - gulp clean  # 清除
  - gulp # 生成