language: node_js # 设置语言

node_js:
  - "8" # 设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

# 指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master

install:
  - npm install # 安装依赖

script:
  - gulp clean # 清除
  - gulp # 生成

after_script:
  # - cd ./dist
  # - ls
  # # - git init
  # - git config user.name "leochan2017"  # 修改name
  # - git config user.email "leochan2017@gmail.com"  #修改email
  # - git status
  # - git add .
  # - git commit -m "Travis CI Auto Builder" # 提交记录包含时间 跟上面更改时区配合
  # - git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master:master #Travis_Token是在Travis中配置环境变量的名称

before_deploy:
  - git config --local user.name "leochan2017"
  - git config --local user.email "leochan2017@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"


# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true

# deploy:
#   provider: releases
#   api_key:
#     secure: aoZDgr9Qyg8nm+jXD6rBNmge7ofb5bakj6DIz4EpVyH/CKZECZsQx4TAA/kCfeCifuo1Y1Ns3CITboOpSOIUytuy9B8L+mhdImo88q2i1Hz4iSMRdCP5UQQxUUxVnAOdWlYlAgVlk9TDYP+qDwreoNn56YvWnAaivsNDREh3VLe1S9qziVxnpFrgzh4xli7CEPuPF0Fh2cN32gC1RCBv5HViF1HFSw0xbR2r67G4jr1T7KMFpo5I0V2kmTL/z2c6zcNoM1L/M0CZAMvvKZtq4AyJj4Rrr87EsSSRogA9j0RBAbR3M73VNkwJxbntXJ6RaDyo6g781ZW5JQCa/b9S3zzm8UBf+d+TayyHvcUxs6XgpLMISmTU8+rXBhDohmUTOBOJ9yDM4As93bzBxJiCjFUI4oLbJ/sKyFaxdTpJHAp9zUwucOmR6RoACIJDYdYOeswXAflI/94CXOaYhTyR8BJwVYCc3UMvDGhQ6uZY2FeBpBUvF9LSrEG6wP/9Gl72RLFTO98iWRm2WqHd4adt/dZb1lm04XP2BdR1wZw7WNCRHsVpnLgD9Wz+4s/Xywr0JaFd/V7LBYsSo/tIWyqjKy9aMQeHEnkDdmvqWQNWjSu5E3Uy9Wvn6AmXZJEcDkjXYEr/eBWtF2p6MSIzwBRPJF4IJtIfqm+k/yl+vSrM4Of8=
#   file: 
#     - "index.html"
#   # file_glob: true
#   # file: dist/*
#   skip_cleanup: true
#   on:
#     repo: leochan2017/kms-editors

deploy:
  provider: releases
  api_key:
    secure: JN0Ainldl0DTonKBwVq4hMLly4MZBOHVhMbXIQAJ4Zo5YnDCU4tfc/0PyeFhdkFTCl9bJbE8cXRTbfS6tViUGgi8iWt4cMYFvzxO7MZ2JFYyPoLLg0SUkFfQ8gxMBFAtFHx/vYz5OmutqXVMcVU9kb7mkGTH9upe9x9GAvvDWCBixmVxddf34HnxZrkcoB9xgR+s9tZXcM5JXQkGikiU/fZUli/7poPQrQ+Bct+R2lUmv+jbcVE74o7ujNC8AaMUPkvUFz3Xx8T4mzzaxGgSmNC9VgGi+3tEq3fgwmCP2fFIuehk8QCjWeoZuTbMfc/wPdxolPzVGyGw3nF1AKptzP4yuwFRPl/O9fhNRuIkiTdS7XZJpnZvr6NG+LOIYrTdxe3HhnTpmd6CUKxiip7MAk0AzX6HdjfMDs3uwCZJ/dLckEitYDfc63IscXmRyKcIW5T4looHsYn++PAGH/xiMoL/RbWhHvGDSKaKX3YR7jbnPcYNQg9WMcOOVXQ3Io0zU8OQ1eeV2j0Dht9uC60OoEkXLozfP1i0E9KhJFDctf9fTyQGECq9I5Qo6mzPGaEAF/LPCpgKL93q1NHV2tO29/bVxofdrIy3HK7GqjKjRGoXEmyGPdAB8CiTA+81FVGteiWGst+jNjUvSa6nowa0nt7jpsmZNclZQAxDKAEx+A0=
  file: index.html
  on:
    repo: leochan2017/kms-editors

env:
 global:
   - GH_REF: github.com/leochan2017/kms-editors.git # 设置GH_REF


# notifications:
#   email:
#     - leochan2017@gmail.com
#   on_success: change
#   on_failure: always